# Generated by Django 4.1.12 on 2024-01-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='walletsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_deposit_wallet', models.CharField(default='8e00r18393111182840847fihkjle', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=50)),
                ('referral_balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=50)),
                ('trade_balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=50)),
                ('profit_balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=50)),
                ('referral_link', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
