# Generated by Django 4.1.12 on 2024-02-15 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('drivers_license', 'Drivers_License'), ('Passport', 'Passport'), ('id_card', 'ID_CARD')], default='Passport', max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Kycs')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='selfies')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
