# Generated by Django 4.2.11 on 2024-03-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('audusd', 'AUDUSD'), ('btcusd', 'BTCUSD'), ('ethusd', 'ETHUSD'), ('euraud', 'EURAUD'), ('eurgbp', 'EURGBP'), ('gbpusd', 'GBPUSD'), ('jpyusd', 'JPYUSD'), ('nzdusd', 'NZDUSD'), ('xauusd', 'XAUUSD')], default='xauusd', max_length=15)),
                ('amount', models.CharField(max_length=15)),
                ('profit', models.CharField(blank=True, max_length=15)),
                ('type', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], default='buy', max_length=7)),
                ('lot_size', models.CharField(max_length=15)),
                ('duration', models.CharField(choices=[('30 minutes', '30 MINUTES'), ('40 minutes', '40 MINUTES'), ('1 hour', '1 HOUR'), ('4 hours', '4 HOURS'), ('8 hours', '8 HOURS'), ('16 hours', '16 HOURS'), ('1 day', '1 DAY')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='open', max_length=10)),
            ],
        ),
    ]
