# Generated by Django 4.1.12 on 2024-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_trade_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='duration',
            field=models.CharField(choices=[('30 minutes', '30 MINUTES'), ('40 minutes', '40 MINUTES'), ('1 hour', '1 HOUR'), ('4 hours', '4 HOURS'), ('8 hours', '8 HOURS'), ('16 hours', '16 HOURS'), ('1 day', '1 DAY')], max_length=20),
        ),
    ]
