# Generated by Django 4.1.12 on 2024-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletsettings',
            old_name='default_deposit_wallet',
            new_name='btc_deposit_wallet',
        ),
        migrations.AddField(
            model_name='walletsettings',
            name='usdt_deposit_wallet',
            field=models.CharField(default='8e00r18393111182840847fihkjle', max_length=150),
        ),
    ]
